package aplicacion.modelo.dominio;
// Generated 10/06/2018 19:00:23 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Clasificaciones generated by hbm2java
 */
public class Clasificacion  implements java.io.Serializable {


     private Integer codigo;
     private int identificador;
     private String descripcion;
     private Set pubClas = new HashSet(0);

    public Clasificacion() {
    }

    public Integer getCodigo() {
        return codigo;
    }

    public void setCodigo(Integer codigo) {
        this.codigo = codigo;
    }

    public int getIdentificador() {
        return identificador;
    }

    public void setIdentificador(int identificador) {
        this.identificador = identificador;
    }

    public String getDescripcion() {
        return descripcion;
    }

    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

	
    public Set getPubClas() {
        return this.pubClas;
    }
    
    public void setPubClas(Set pubClas) {
        this.pubClas = pubClas;
    }




}


